-- 코드를 작성해주세요
WITH ROOT_ITEMS AS (
    SELECT ITEM_ID
      FROM ITEM_TREE
     WHERE PARENT_ITEM_ID IS NULL
)

SELECT ITEM_ID, ITEM_NAME
  FROM ITEM_INFO
 WHERE ITEM_ID IN (SELECT * FROM ROOT_ITEMS);