-- 코드를 작성해주세요
SELECT e.ID,
       e.GENOTYPE,
       sub.GENOTYPE AS PARENT_GENOTYPE
  FROM ECOLI_DATA e
 INNER JOIN ECOLI_DATA sub
    ON e.PARENT_ID = sub.ID
 WHERE e.GENOTYPE & sub.GENOTYPE = sub.GENOTYPE
 ORDER BY e.ID ASC;